version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: safething-drafts-hello-world_web_1
      APP_PORT: 3000
    
  web:
    image: bochaco/hello-world:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PORTAINER_HOST: host.docker.internal
      NODES_RPC_HOST: host.docker.internal
    extra_hosts:
      "host.docker.internal:host-gateway"
